spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: service-vod
  servlet:
    multipart:
      max-request-size: 1024MB
      max-file-size: 1024MB
  profiles:
    active: dev
server:
  port: 8003
aliyun:
  vod:
    file:
      keysecret:
      keyid:
