server:
  port: 8001
spring:
  application:
    name: service-acl
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    dbcp2:
      driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000
mybatis-plus:
  #configuration:
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/itguigu/service/edu/mapper/xml/*.xml
