spring:
  cloud:
    # nacos服务地址
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #服务名
  application:
    name: service-oss
  #环境设置：dev、test、prod
  profiles:
    active: dev
#服务端口
server:
  port: 8002
#阿里云 OSS
aliyun:
  oss:
    file:
      keysecret:
      endpoint:
      bucketname:
      keyid:
