server:
  port: 6001
spring:
  application:
    name: eureka
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false #是否将自己注册到eureka中
    fetch-registry: false #是否从eureka中获取信息
    service-url:
      #defaultZone: http://peer2:8002/eureka,http://peer3:8003/eureka
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
